### ISSUE TITLE
referencia de arquivos less/js

### ISSUE THREAD

**Issue by kellerkichel** [Ceicom/ceicom-cli#3]
Ao criar um combo, nos arquivos js e less e a referencia do js dentro do arquivo aspx ele mantêm a extensão aspx, pode ser removida neste caso, segue print:

![image](https://user-images.githubusercontent.com/4204423/47871486-fce8c880-ddea-11e8-9d26-6fe589b8271e.png)

**Comment by emanoelqueiroz** [comment]
Mas e agora, se eu colocar essa regra no combo, não ficaria estranho criar um js no pages, template e less com um caminho `home/default.js`?

Acho que vamos ter q dar uma conversada sobre esse cara

**Comment by kellerkichel** [comment]
vamos trabalhar então sempre removendo o final da solicitação nos combos,
ex:
```home/default.aspx``` gera os js e less ```home.[less ou js]```

se o caminho de solicitação for: 
```home/list/detail.aspx``` gera os js e less dentro da pasta home ```list.[less ou js]```
